analytics_retail:
  target: DEV
  outputs:
    DEV:
      account:  "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads:  4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse:  "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      query_tag:  "{{ env_var('SNOWFLAKE_QUERY_TAG') }}"
    PROD:
      account:  "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads:  4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse:  "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      query_tag:  "{{ env_var('SNOWFLAKE_QUERY_TAG') }}"

    TST:
      account:  "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      threads:  4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse:  "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      query_tag:  "{{ env_var('SNOWFLAKE_QUERY_TAG') }}"
   