analytics_retail:
  target: dev
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse:  "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
    prod:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse:  "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
    tst:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse:  "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
